name: Continous Integration
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: Install stack (MacOS)
      #   run: curl -sSL https://get.haskellstack.org/ | sh
      #   if: matrix.os == 'macos-10.15'

      - name: Install stack (Windows)
        run: choco install haskell-stack
        if: matrix.os == 'windows-2019'

      - name: Cache dependencies (Unix)
        uses: actions/cache@v1
        if: matrix.os != 'windows-2019'
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('text-regex-replace/stack.yaml.lock') }}-${{ hashFiles('text-regex-replace/text-regex-replace.cabal') }}

      - name: Cache dependencies (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Roaming\stack'
          key: ${{ runner.os }}-store-${{ hashFiles('text-regex-replace/stack.yaml.lock') }}-${{ hashFiles('text-regex-replace/generator.cabal') }}

      - name: Cache GHC (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          key: ghc-${{ hashFiles('text-regex-replace/stack.yaml.lock') }}

      - name: Build text-regex-replace
        run: cd ~/work/text-regex-replace/text-regex-replace && stack build
        
      - name: Test text-regex-replace
        run: cd ~/work/text-regex-replace/text-regex-replace && stack test

      - name: Package text-regex-replace
        shell: bash
        run: |
          mkdir package
          cd ~/work/text-regex-replace/text-regex-replace
          dir=$(stack path --dist-dir)/build/text-regex-replace
          [[ -e "$dir/text-regex-replace" ]] && cp "$dir/text-regex-replace" ../package/text-regex-replace
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: text-regex-replace-${{ runner.os }}
          path: package
